name: 'Setup environment'

inputs:
  source-path:
    description: 'OS name (linux | darwin | win32)'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@master
      with:
        node-version: 16.18.0

    - name: Install npm dependencies
      run: npm ci
      shell: bash
