name: Build and test binary

on:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-20.04

    timeout-minutes: 10

    env:
      DISPLAY: ":99.0"

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: npm run start-linux

      - name: Install WM
        run: sudo apt install fluxbox

      - name: Run X11
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          sleep 3
          fluxbox &

      - name: Prepare test
        run: |
          cd test
          rm -rf dummy
          npm i

      - name: Test
        run: |
          cd test
          npm run test

      - name: Compress deps
        run: |
          zip -r linux.zip ./deps/linux/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux.zip
          path: ./linux.zip
